name: Push event test

on:
    push:
        branches:
            - 'master'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: run a one-line script
              run: echo hello world